[package]
name = "modio"
version = "0.1.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]

[dependencies]
futures = "0.1"
http = "0.1"
hyper = "0.12"
hyper-multipart-rfc7578 = "0.2.0-alpha1"
hyper-tls = "0.3"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
tokio-core = "0.1"
url = "1.7"
url_serde = "0.2"

[dev-dependencies]
tokio = "0.1"
