[package]
name = "modio"
version = "0.2.0" # don't forget to update html_root_url
description = "Rust interface for mod.io"
readme = "README.md"
documentation = "https://docs.rs/modio"
repository = "https://github.com/nickelc/modio-rs"
license = "MIT/Apache-2.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]
keywords = ["modio", "hyper"]
categories = ["api-bindings", "web-programming::http-client"]

[dependencies]
futures = "0.1"
http = "0.1"
hyper = "0.12"
hyper-multipart-rfc7578 = "0.2.0-alpha2"
hyper-tls = "0.3"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"
url_serde = "0.2"

[dev-dependencies]
md5 = "0.3"
reqwest = "0.8"
tokio = "0.1"
