[package]
name = "modio"
version = "0.1.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
tokio-core = "0.1"
url = "1.7"
url_serde = "0.2"

[dependencies.hyper-tls]
optional = true
version = "0.1.2"

[features]
default = ["tls"]
tls = ["hyper-tls"]
