[package]
name = "modio"
version = "0.3.0" # don't forget to update html_root_url
description = "Rust interface for mod.io"
readme = "README.md"
documentation = "https://docs.rs/modio"
repository = "https://github.com/nickelc/modio-rs"
license = "MIT/Apache-2.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]
keywords = ["modio", "hyper"]
categories = ["api-bindings", "web-programming::http-client"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "0.1"
http = "0.1"
hyper = "0.12"
mime = "0.3"
mpart-async = { version = "0.2", default-features = false }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-codec = "0.1"
tokio-fs = "0.1"
tokio-io = "0.1"
url = "1.7"
url_serde = "0.2"

[dependencies.hyper-tls]
version = "0.3"
optional = true

[dependencies.hyper-rustls]
version = "0.15"
optional = true

[dev-dependencies]
md5 = "0.3"
tokio = "0.1"

[features]
default = ["tls"]
tls = ["hyper-tls"]
rustls = ["hyper-rustls"]
